apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- manifests.yaml
- service.yaml
- certificate.yaml

configurations:
- kustomizeconfig.yaml

patches:
- path: webhook_patch.yaml
  target:
    kind: ValidatingWebhookConfiguration
- path: manager_webhook_patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
    namespace: system
