apiVersion: readiness.node.x-k8s.io/v1alpha1
kind: NodeReadinessRuleReport
metadata:
  labels:
    app.kubernetes.io/name: nrrcontroller
    app.kubernetes.io/managed-by: kustomize
  name: nodereadinessrulereport-sample
spec:
  # TODO(user): Add fields here
