apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-certs
  namespace: system
spec:
  commonName: metrics
  dnsNames:
  - nrr-controller-manager-metrics-service.nrr-system.svc
  - nrr-controller-manager-metrics-service.nrr-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: metrics-server-cert
