apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- policy.yaml
- binding.yaml

labels:
- pairs:
    app.kubernetes.io/name: nrrcontroller
    app.kubernetes.io/component: admission-policy
